# Generated by Django 5.0.7 on 2024-08-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Message', models.TextField(max_length=100)),
            ],
        ),
    ]
