# Generated by Django 5.0.7 on 2024-08-19 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=30, null=True)),
                ('designation', models.TextField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('doc_img', models.ImageField(null=True, upload_to='doctors')),
                ('exp', models.IntegerField(null=True)),
                ('qualification', models.CharField(max_length=50, null=True)),
                ('opening_time', models.CharField(max_length=30, null=True)),
                ('day', models.CharField(max_length=30, null=True)),
                ('place', models.CharField(max_length=30, null=True)),
                ('doc_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_name', to='myapp.department')),
            ],
        ),
    ]
