# Generated by Django 5.0.7 on 2024-08-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='my_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
