# Generated by Django 5.0.7 on 2024-08-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_appointment_my_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='my_datetime',
            new_name='booking_datetime',
        ),
    ]
