# Generated by Django 5.0.7 on 2024-08-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_my_datetime_appointment_booking_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('video', models.FileField(null=True, upload_to='video')),
                ('description', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
