# Generated by Django 5.0.7 on 2024-08-22 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=400, null=True)),
                ('about_role', models.CharField(max_length=400, null=True)),
                ('requirements', models.CharField(max_length=400, null=True)),
                ('company_name', models.CharField(max_length=40, null=True)),
                ('about_name', models.CharField(max_length=500, null=True)),
                ('jobtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='myapp.jobtype')),
            ],
        ),
    ]
