# Generated by Django 5.0.7 on 2024-08-22 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_jobtype_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, null=True)),
                ('lastname', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('qualification', models.CharField(max_length=50, null=True)),
                ('biodata', models.FileField(null=True, upload_to='biodata')),
                ('apply_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply', to='myapp.job')),
            ],
        ),
    ]
